### PR TITLE
[products] Add String US and Neon Intl

### PR DESCRIPTION
**Pull request by alessio-palumbo**

### CODE REVIEW

**Comment by delfick** [comment]
@alessio-palumbo it seems the community lan docs also need them added....

**Comment by ristomatti** [comment]
@delfick As a community forum legend, do you happen to have some info if the developer docs will disappear as well with the community forum? I'm referring to this https://community.lifx.com/t/developer-zone-forum-closure/9294

**Comment by delfick** [comment]
@ristomatti I haven't worked for LIFX since July 2021 and don't visit the forum/reddit anymore so I'm not in that loop. I'm sure @alessio-palumbo or the email mentioned in that post will have answers for you!

**Comment by alessio-palumbo** [comment]
@ristomatti the developer docs won't be affected and will continue to be available.

**Comment by ristomatti** [comment]
@alessi-palumbo Good to hear, thank you for the clarification.

For the record, it was this excerpt from the community forum announcement that caused the doubt:

> If you are working on a specific project to integrate with the LIFX API and LAN and want to chat with us privately, please reach out via email at [support@lifx.com](mailto:support@lifx.com) and we will connect you with someone who can help.

Particularly it sounded to me like LIFX is moving towards a more closed model of integration with 3rd parties.

**Pull request merged**
